In [1]:
import torch
print("pytorch: v",torch.__version__ , "cuda:", torch.version.cuda, "cudnn:", torch.backends.cudnn.version())

pytorch: v 2.7.1+cu126 cuda: 12.6 cudnn: 90501


In [2]:
heights = [189, 170, 189, 163, 183, 171, 185,
168, 173, 183, 173, 173, 175, 178,
183, 193, 178, 173, 174, 183, 183,
180, 168, 180, 170, 178, 182, 180,
183, 178, 182, 188, 175, 179, 183,
193, 182, 183, 177, 185, 188, 188,
182, 185, 191, 183]

height_tensor = torch.tensor(heights, dtype=torch.float64)
print(height_tensor)
print(height_tensor.shape)

tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178., 183., 193., 178., 173., 174., 183., 183., 180., 168., 180.,
        170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183., 193.,
        182., 183., 177., 185., 188., 188., 182., 185., 191., 183.],
       dtype=torch.float64)
torch.Size([46])


In [9]:
height_in_feet= height_tensor / 30.48
print(height_in_feet)
height_2_meatures = torch.cat( [height_tensor, height_in_feet], dim=0)

print(height_2_meatures.shape)
heights_reshaped=height_2_meatures.reshape(2, -1)  # -1 means infer the size of this dimension
print(heights_reshaped.shape)
print(heights_reshaped)

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399, 6.0039, 6.3320, 5.8399, 5.6759,
        5.7087, 6.0039, 6.0039, 5.9055, 5.5118, 5.9055, 5.5774, 5.8399, 5.9711,
        5.9055, 6.0039, 5.8399, 5.9711, 6.1680, 5.7415, 5.8727, 6.0039, 6.3320,
        5.9711, 6.0039, 5.8071, 6.0696, 6.1680, 6.1680, 5.9711, 6.0696, 6.2664,
        6.0039], dtype=torch.float64)
torch.Size([92])
torch.Size([2, 46])
tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
         168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
         183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
         180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
         183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
         193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
         182.0000, 185.0000, 191.0000, 183.0000],
 

In [19]:
print(torch.median(heights_reshaped[0, :]))
print(torch.median(heights_reshaped[1, :]))
print(torch.mean(heights_reshaped[0, :]))
values, indices=torch.max(heights_reshaped, dim=0)
print(values)
print(indices)


tensor(182., dtype=torch.float64)
tensor(5.9711, dtype=torch.float64)
tensor(180.0652, dtype=torch.float64)
tensor([189., 170., 189., 163., 183., 171., 185., 168., 173., 183., 173., 173.,
        175., 178., 183., 193., 178., 173., 174., 183., 183., 180., 168., 180.,
        170., 178., 182., 180., 183., 178., 182., 188., 175., 179., 183., 193.,
        182., 183., 177., 185., 188., 188., 182., 185., 191., 183.],
       dtype=torch.float64)
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
