In [6]:
import faiss
import numpy as np

# vectors= np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
vectors= np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1],[1, 1,0],[0, 1, 1]], dtype=np.float32)
faiss.normalize_L2(vectors)
print("Normalized Vectors:\n", vectors)


Normalized Vectors:
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.         1.        ]
 [0.70710677 0.70710677 0.        ]
 [0.         0.70710677 0.70710677]]


In [7]:
d = vectors.shape[0]
print ("Dimension of vectors:", d)
d= vectors.shape[1]
print ("Dimension of vectors:", d)

Dimension of vectors: 5
Dimension of vectors: 3


In [17]:
index = faiss.IndexFlatIP(d)
index.add(vectors)
query=np.array([[1, 1, 1]], dtype=np.float32)
faiss.normalize_L2(query)
print("Query Vector:\n", query)
D, I = index.search(query, 3)  # Search for the 3 nearest neighbors
print("Distances:\n", D)
print("Indices:\n", I)

Query Vector:
 [[0.57735026 0.57735026 0.57735026]]
Distances:
 [[0.81649655 0.81649655 0.57735026]]
Indices:
 [[4 3 2]]
